"""initial_schema

Revision ID: 73774840e662
Revises: 
Create Date: 2026-05-03 22:23:42.230799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '73774840e662'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('show_phone', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('auth_provider', sa.Enum('google', 'facebook', 'email', name='authprovider'), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('language', sa.Enum('en', 'ar', name='language'), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('seller_id', sa.BLOB(length=16), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('transmission', sa.Enum('automatic', 'manual', name='transmission'), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('condition', sa.Enum('new', 'used', 'used_like_new', name='condition'), nullable=False),
    sa.Column('body_type', sa.String(length=50), nullable=True),
    sa.Column('engine_size', sa.String(length=20), nullable=True),
    sa.Column('fuel_type', sa.Enum('petrol', 'diesel', 'hybrid', 'electric', name='fueltype'), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('show_phone', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'sold', 'expired', name='listingstatus'), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_district'), 'listings', ['district'], unique=False)
    op.create_index(op.f('ix_listings_make'), 'listings', ['make'], unique=False)
    op.create_index(op.f('ix_listings_model'), 'listings', ['model'], unique=False)
    op.create_index(op.f('ix_listings_seller_id'), 'listings', ['seller_id'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_index(op.f('ix_listings_vin'), 'listings', ['vin'], unique=False)
    op.create_index(op.f('ix_listings_year'), 'listings', ['year'], unique=False)
    op.create_table('badges',
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('listing_id', sa.BLOB(length=16), nullable=False),
    sa.Column('badge_type', sa.Enum('one_owner', 'service_book_verified', name='badgetype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='badgestatus'), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by', sa.BLOB(length=16), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'badge_type', name='uq_listing_badge_type')
    )
    op.create_index(op.f('ix_badges_listing_id'), 'badges', ['listing_id'], unique=False)
    op.create_index(op.f('ix_badges_status'), 'badges', ['status'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('buyer_id', sa.BLOB(length=16), nullable=False),
    sa.Column('seller_id', sa.BLOB(length=16), nullable=False),
    sa.Column('listing_id', sa.BLOB(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id', 'listing_id', name='uq_buyer_listing')
    )
    op.create_table('favorites',
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('user_id', sa.BLOB(length=16), nullable=False),
    sa.Column('listing_id', sa.BLOB(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'listing_id', name='uq_user_listing')
    )
    op.create_table('photos',
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('listing_id', sa.BLOB(length=16), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('photo_type', sa.Enum('front', 'side', 'interior', 'other', name='phototype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_listing_id'), 'photos', ['listing_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BLOB(length=16), nullable=False),
    sa.Column('conversation_id', sa.BLOB(length=16), nullable=False),
    sa.Column('sender_id', sa.BLOB(length=16), nullable=False),
    sa.Column('content_type', sa.Enum('text', 'image', 'voice_note', name='contenttype'), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_duration_sec', sa.Integer(), nullable=True),
    sa.Column('file_waveform', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_photos_listing_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_table('favorites')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_badges_status'), table_name='badges')
    op.drop_index(op.f('ix_badges_listing_id'), table_name='badges')
    op.drop_table('badges')
    op.drop_index(op.f('ix_listings_year'), table_name='listings')
    op.drop_index(op.f('ix_listings_vin'), table_name='listings')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_seller_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_model'), table_name='listings')
    op.drop_index(op.f('ix_listings_make'), table_name='listings')
    op.drop_index(op.f('ix_listings_district'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###